"""
Godot Agent 健壮性压力测试: 原子性回滚验证
"""

import os
import shutil
from pathlib import Path
import sys

# 添加项目路径
sys.path.append(str(Path(__file__).parent.parent))

from agent_system.router import GodotAgentRouter
from agent_system.models import TaskStatus

def setup_test_env():
    """准备测试环境"""
    project_dir = Path("test_sandbox")
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir()
    
    scripts_dir = project_dir / "scripts"
    scripts_dir.mkdir()
    
    # 创建一个重要文件
    original_content = "extends Node\n# ORIGINAL_CODE_MARKER"
    script_file = scripts_dir / "collision_test.gd"
    with open(script_file, "w", encoding="utf-8") as f:
        f.write(original_content)
        
    return project_dir, script_file, original_content

def test_atomic_rollback():
    print("🚀 开始原子性回滚深度检测...")
    project_dir, script_file, original_content = setup_test_env()
    
    # 初始化 Router, 注入沙盒路径
    router = GodotAgentRouter(godot_project_path=str(project_dir))
    
    # 指令: 修改现有脚本, 然后触发一个会失败的任务 (通过请求一个不存在的场景)
    # 我们通过强制修改 Router 的规划逻辑来制造一个中途失败的场景
    task = router.plan("修改 collision_test.gd 并运行一个不存在的测试")
    
    # 模拟执行流程
    print("1. 执行编排计划...")
    task = router.execute_plan(task)
    
    # 验证最终状态
    print(f"2. 最终任务状态: {task.status.value}")
    
    # 深度检测: 文件内容是否还原
    with open(script_file, "r", encoding="utf-8") as f:
        current_content = f.read()
        
    if current_content == original_content:
        print("✅ 检测通过: 原始文件内容已完美还原。")
    else:
        print("❌ 检测失败: 文件内容被破坏, 未能正确回滚。")
        print(f"当前内容:\n{current_content}")

    # 检测: 临时产物是否清理
    new_scene = project_dir / "scenes/AutoGenerated.tscn"
    if not new_scene.exists():
        print("✅ 检测通过: 失败步骤产生的临时产物已清理。")
    else:
        print("❌ 检测失败: 临时产物遗留在文件系统中。")

if __name__ == "__main__":
    test_atomic_rollback()
