extends Node

class_name LiveUiConfirmAudioRouter

# Auto-generated by manage_presentation_pipeline for `live_ui_confirm`.
@export var default_stream: AudioStream = preload("res://assets/audio/live_ui_confirm.ogg")
const EVENT_TO_BUS := {"live_ui_confirm": "UI"}

func play_event(event_name: String, parent: Node = self) -> Node:
	if not EVENT_TO_BUS.has(event_name):
		push_warning("Unknown audio event: %s" % event_name)
		return null
	var player := AudioStreamPlayer.new()
	player.bus = EVENT_TO_BUS[event_name]
	player.autoplay = false
	player.stream = default_stream
	parent.add_child(player)
	player.name = "%s_player" % event_name
	if default_stream != null and not player.autoplay:
		player.play()
	return player
