"""
Contract catalog and migration entrypoints.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .core import (
    BALANCE_ANALYSIS_SCHEMA_VERSION,
    BALANCE_VERSION_COMPARE_SCHEMA_VERSION,
    FEATURE_CONTEXT_SCHEMA_VERSION,
    PERFORMANCE_SUMMARY_SCHEMA_VERSION,
    PRESENTATION_PROFILE_SCHEMA_VERSION,
    LIVEOPS_PROFILE_SCHEMA_VERSION,
    GAME_CREATION_PROFILE_SCHEMA_VERSION,
    GAME_CREATION_TEMPLATE_MIGRATION_SCHEMA_VERSION,
    SCENE_GRAPH_AUDIT_SCHEMA_VERSION,
    GAME_CREATION_REVIEW_SCHEMA_VERSION,
    GAME_CREATION_REPLAY_SCHEMA_VERSION,
    SCENE_GRAPH_SNAPSHOT_SCHEMA_VERSION,
    ROADMAP_STATUS_SCHEMA_VERSION,
    PLATFORM_DELIVERY_PROFILE_SCHEMA_VERSION,
    OUTSOURCE_DELIVERY_GATE_SCHEMA_VERSION,
    ASSET_REVIEW_WORKFLOW_SCHEMA_VERSION,
    BUILD_RUN_MATRIX_SCHEMA_VERSION,
    SCENE_OWNERSHIP_BOARD_SCHEMA_VERSION,
    RELEASE_CAPABILITY_REGISTRY_SCHEMA_VERSION,
    RELEASE_CAPABILITY_POLICY_SCHEMA_VERSION,
    RELEASE_RUNTIME_ASSEMBLY_SCHEMA_VERSION,
    RELEASE_DELIVERY_READINESS_SCHEMA_VERSION,
    RELEASE_LIVE_EVENT_STREAM_SCHEMA_VERSION,
    RELEASE_LIVE_DISPATCH_PREFLIGHT_SCHEMA_VERSION,
    RELEASE_LIVE_DISPATCH_AUDIT_SCHEMA_VERSION,
    RELEASE_ARTIFACT_MANIFEST_SCHEMA_VERSION,
    RELEASE_PROMOTION_PLAN_SCHEMA_VERSION,
    RELEASE_PROMOTION_HISTORY_SCHEMA_VERSION,
    RELEASE_EXECUTION_STATUS_SCHEMA_VERSION,
    PRODUCTION_READINESS_SCHEMA_VERSION,
    PRODUCTION_SCENARIO_SCHEMA_VERSION,
    RELEASE_CANDIDATE_CHECKLIST_SCHEMA_VERSION,
    AGENT_PROVIDER_COMPAT_SCHEMA_VERSION,
    RELEASE_REVIEW_BUNDLE_SCHEMA_VERSION,
    GOVERNANCE_POLICY_SCHEMA_VERSION,
    CHANGE_ADMISSION_SCHEMA_VERSION,
    GOVERNANCE_ENFORCEMENT_SCHEMA_VERSION,
    QUALITY_GATE_SCHEMA_VERSION,
    RELEASE_QA_EVIDENCE_SCHEMA_VERSION,
    RELEASE_SUMMARY_SCHEMA_VERSION,
    TELEMETRY_SUMMARY_SCHEMA_VERSION,
)
from .skill_results import SKILL_RESULT_SCHEMA_VERSION


CONTRACT_CATALOG_SCHEMA_VERSION = "1.0"


def build_contract_catalog() -> Dict[str, Any]:
    contracts: List[Dict[str, Any]] = [
        {
            "contract_name": "balance_analysis",
            "current_version": BALANCE_ANALYSIS_SCHEMA_VERSION,
            "supported_versions": [BALANCE_ANALYSIS_SCHEMA_VERSION],
            "entrypoint": "normalize_balance_analysis",
            "normalization_strategy": "normalize_on_read",
            "notes": "Enemy / quest / loot balance checks, score, metrics, risk summary",
        },
        {
            "contract_name": "balance_version_compare",
            "current_version": BALANCE_VERSION_COMPARE_SCHEMA_VERSION,
            "supported_versions": [BALANCE_VERSION_COMPARE_SCHEMA_VERSION],
            "entrypoint": "normalize_balance_version_compare",
            "normalization_strategy": "normalize_on_read",
            "notes": "Baseline-vs-candidate balance score, issue, warning, and metric drift comparison",
        },
        {
            "contract_name": "telemetry_summary",
            "current_version": TELEMETRY_SUMMARY_SCHEMA_VERSION,
            "supported_versions": [TELEMETRY_SUMMARY_SCHEMA_VERSION],
            "entrypoint": "normalize_telemetry_summary",
            "normalization_strategy": "normalize_on_read",
            "notes": "Telemetry event catalog, session summary, crash/uncataloged event health",
        },
        {
            "contract_name": "performance_summary",
            "current_version": PERFORMANCE_SUMMARY_SCHEMA_VERSION,
            "supported_versions": [PERFORMANCE_SUMMARY_SCHEMA_VERSION],
            "entrypoint": "normalize_performance_summary",
            "normalization_strategy": "normalize_on_read",
            "notes": "Performance profile, baseline comparison, and richer budget checks",
        },
        {
            "contract_name": "presentation_profile",
            "current_version": PRESENTATION_PROFILE_SCHEMA_VERSION,
            "supported_versions": [PRESENTATION_PROFILE_SCHEMA_VERSION],
            "entrypoint": "normalize_presentation_profile",
            "normalization_strategy": "normalize_on_read",
            "notes": "P10 animation / VFX / shader / audio presentation manifest and generated scaffold contract",
        },
        {
            "contract_name": "liveops_profile",
            "current_version": LIVEOPS_PROFILE_SCHEMA_VERSION,
            "supported_versions": [LIVEOPS_PROFILE_SCHEMA_VERSION],
            "entrypoint": "normalize_liveops_profile",
            "normalization_strategy": "normalize_on_read",
            "notes": "P12 remote config and experiment catalog manifest contract for LiveOps workflows",
        },
        {
            "contract_name": "game_creation_profile",
            "current_version": GAME_CREATION_PROFILE_SCHEMA_VERSION,
            "supported_versions": [GAME_CREATION_PROFILE_SCHEMA_VERSION],
            "entrypoint": "normalize_game_creation_profile",
            "normalization_strategy": "normalize_on_read",
            "notes": "Zero-to-playable game creation plan/apply contract for local Web and MCP workflows",
        },
        {
            "contract_name": "scene_graph_audit",
            "current_version": SCENE_GRAPH_AUDIT_SCHEMA_VERSION,
            "supported_versions": [SCENE_GRAPH_AUDIT_SCHEMA_VERSION],
            "entrypoint": "normalize_scene_graph_audit",
            "normalization_strategy": "normalize_on_read",
            "notes": "Plan-vs-Godot scene graph audit for generated nodes, scripts, signals, and response wiring",
        },
        {
            "contract_name": "scene_graph_snapshot",
            "current_version": SCENE_GRAPH_SNAPSHOT_SCHEMA_VERSION,
            "supported_versions": [SCENE_GRAPH_SNAPSHOT_SCHEMA_VERSION],
            "entrypoint": "normalize_scene_graph_snapshot",
            "normalization_strategy": "normalize_on_read",
            "notes": "Live Godot editor scene graph snapshot reported by the plugin for runtime plan-vs-editor monitoring",
        },
        {
            "contract_name": "game_creation_review",
            "current_version": GAME_CREATION_REVIEW_SCHEMA_VERSION,
            "supported_versions": [GAME_CREATION_REVIEW_SCHEMA_VERSION],
            "entrypoint": "normalize_game_creation_review",
            "normalization_strategy": "normalize_on_read",
            "notes": "Acceptance review summary for generated game prototypes, combining checklist, module review, and scene graph audit",
        },
        {
            "contract_name": "game_creation_replay",
            "current_version": GAME_CREATION_REPLAY_SCHEMA_VERSION,
            "supported_versions": [GAME_CREATION_REPLAY_SCHEMA_VERSION],
            "entrypoint": "normalize_game_creation_replay",
            "normalization_strategy": "normalize_on_read",
            "notes": "Input replay runner plan and generated headless script evidence for P19 game creation prototypes",
        },
        {
            "contract_name": "game_creation_template_migration",
            "current_version": GAME_CREATION_TEMPLATE_MIGRATION_SCHEMA_VERSION,
            "supported_versions": [GAME_CREATION_TEMPLATE_MIGRATION_SCHEMA_VERSION],
            "entrypoint": "normalize_game_creation_template_migration",
            "normalization_strategy": "normalize_on_read",
            "notes": "Plan-only migration strategy for moving a P19 generated prototype between zero-to-playable templates",
        },
        {
            "contract_name": "roadmap_status",
            "current_version": ROADMAP_STATUS_SCHEMA_VERSION,
            "supported_versions": [ROADMAP_STATUS_SCHEMA_VERSION],
            "entrypoint": "normalize_roadmap_status",
            "normalization_strategy": "normalize_on_read",
            "notes": "Machine-readable roadmap progress ledger for done / partial / pending project phases and next actions",
        },
        {
            "contract_name": "platform_delivery_profile",
            "current_version": PLATFORM_DELIVERY_PROFILE_SCHEMA_VERSION,
            "supported_versions": [PLATFORM_DELIVERY_PROFILE_SCHEMA_VERSION],
            "entrypoint": "normalize_platform_delivery_profile",
            "normalization_strategy": "normalize_on_read",
            "notes": "P13 platform export, savegame schema, services, and multiplayer baseline contract",
        },
        {
            "contract_name": "outsource_delivery_gate",
            "current_version": OUTSOURCE_DELIVERY_GATE_SCHEMA_VERSION,
            "supported_versions": [OUTSOURCE_DELIVERY_GATE_SCHEMA_VERSION],
            "entrypoint": "normalize_outsource_delivery_gate",
            "normalization_strategy": "normalize_on_read",
            "notes": "P15 outsource delivery manifest, package root, metadata, and package file readiness gate",
        },
        {
            "contract_name": "asset_review_workflow",
            "current_version": ASSET_REVIEW_WORKFLOW_SCHEMA_VERSION,
            "supported_versions": [ASSET_REVIEW_WORKFLOW_SCHEMA_VERSION],
            "entrypoint": "normalize_asset_review_workflow",
            "normalization_strategy": "normalize_on_read",
            "notes": "P15 asset review board, per-asset approval state, reviewer, and review manifest consistency",
        },
        {
            "contract_name": "build_run_matrix",
            "current_version": BUILD_RUN_MATRIX_SCHEMA_VERSION,
            "supported_versions": [BUILD_RUN_MATRIX_SCHEMA_VERSION],
            "entrypoint": "normalize_build_run_matrix",
            "normalization_strategy": "normalize_on_read",
            "notes": "P15 build/export targets, production gates, and non-live/live execution lanes in one matrix contract",
        },
        {
            "contract_name": "release_capability_registry",
            "current_version": RELEASE_CAPABILITY_REGISTRY_SCHEMA_VERSION,
            "supported_versions": [RELEASE_CAPABILITY_REGISTRY_SCHEMA_VERSION],
            "entrypoint": "normalize_release_capability_registry",
            "normalization_strategy": "normalize_on_read",
            "notes": "Explicit control-plane capability taxonomy for release, runtime, distribution, and identity surfaces",
        },
        {
            "contract_name": "release_capability_policy",
            "current_version": RELEASE_CAPABILITY_POLICY_SCHEMA_VERSION,
            "supported_versions": [RELEASE_CAPABILITY_POLICY_SCHEMA_VERSION],
            "entrypoint": "normalize_release_capability_policy",
            "normalization_strategy": "normalize_on_read",
            "notes": "Route-scoped policy snapshot separating capability registration from invocation allowance",
        },
        {
            "contract_name": "release_runtime_assembly_snapshot",
            "current_version": RELEASE_RUNTIME_ASSEMBLY_SCHEMA_VERSION,
            "supported_versions": [RELEASE_RUNTIME_ASSEMBLY_SCHEMA_VERSION],
            "entrypoint": "normalize_release_runtime_assembly_snapshot",
            "normalization_strategy": "normalize_on_read",
            "notes": "Invocation-scoped runtime assembly snapshot composed from capability policy, identity boundary, and optional runner baseline",
        },
        {
            "contract_name": "release_delivery_readiness",
            "current_version": RELEASE_DELIVERY_READINESS_SCHEMA_VERSION,
            "supported_versions": [RELEASE_DELIVERY_READINESS_SCHEMA_VERSION],
            "entrypoint": "normalize_release_delivery_readiness",
            "normalization_strategy": "normalize_on_read",
            "notes": "Deliverable-level closure snapshot aggregating external identity boundary, self-hosted workflow evidence, and external distribution delivery state",
        },
        {
            "contract_name": "release_live_event_stream",
            "current_version": RELEASE_LIVE_EVENT_STREAM_SCHEMA_VERSION,
            "supported_versions": [RELEASE_LIVE_EVENT_STREAM_SCHEMA_VERSION],
            "entrypoint": "normalize_release_live_event_stream",
            "normalization_strategy": "normalize_on_read",
            "notes": "Release live gate event timeline synthesized from workflow steps, runtime lanes, automation gate, and invocation context",
        },
        {
            "contract_name": "release_live_dispatch_preflight",
            "current_version": RELEASE_LIVE_DISPATCH_PREFLIGHT_SCHEMA_VERSION,
            "supported_versions": [RELEASE_LIVE_DISPATCH_PREFLIGHT_SCHEMA_VERSION],
            "entrypoint": "normalize_release_live_dispatch_preflight",
            "normalization_strategy": "normalize_on_read",
            "notes": "GitHub workflow dispatch readiness snapshot for the real release-live-gates self-hosted lane",
        },
        {
            "contract_name": "release_live_dispatch_audit",
            "current_version": RELEASE_LIVE_DISPATCH_AUDIT_SCHEMA_VERSION,
            "supported_versions": [RELEASE_LIVE_DISPATCH_AUDIT_SCHEMA_VERSION],
            "entrypoint": "normalize_release_live_dispatch_audit",
            "normalization_strategy": "normalize_on_read",
            "notes": "Durable audit artifact for workflow dispatch preflight, request_auth, and real GitHub run outcome",
        },
        {
            "contract_name": "release_artifact_manifest",
            "current_version": RELEASE_ARTIFACT_MANIFEST_SCHEMA_VERSION,
            "supported_versions": [RELEASE_ARTIFACT_MANIFEST_SCHEMA_VERSION],
            "entrypoint": "normalize_release_artifact_manifest",
            "normalization_strategy": "normalize_on_read",
            "notes": "Machine-readable CI/live artifact manifest with runtime lanes, event stream, runtime assembly, and execution delivery readiness",
        },
        {
            "contract_name": "scene_ownership_board",
            "current_version": SCENE_OWNERSHIP_BOARD_SCHEMA_VERSION,
            "supported_versions": [SCENE_OWNERSHIP_BOARD_SCHEMA_VERSION],
            "entrypoint": "normalize_scene_ownership_board",
            "normalization_strategy": "normalize_on_read",
            "notes": "P15 scene ownership hints, lock states, and per-scene collaboration board for shared editing",
        },
        {
            "contract_name": "release_promotion_plan",
            "current_version": RELEASE_PROMOTION_PLAN_SCHEMA_VERSION,
            "supported_versions": [RELEASE_PROMOTION_PLAN_SCHEMA_VERSION],
            "entrypoint": "normalize_release_promotion_plan",
            "normalization_strategy": "normalize_on_read",
            "notes": "P16 promotion decision contract composed from RC, build matrix, signoffs, evidence bundle, deployment rehearsal, rollback rehearsal, agent compatibility, and scene collaboration state",
        },
        {
            "contract_name": "release_review_bundle",
            "current_version": RELEASE_REVIEW_BUNDLE_SCHEMA_VERSION,
            "supported_versions": [RELEASE_REVIEW_BUNDLE_SCHEMA_VERSION],
            "entrypoint": "build_release_review_bundle",
            "normalization_strategy": "normalize_on_read",
            "notes": "Structured review bundle for build/release handoff: change summary, acceptance checklist, known issues, artifact links, and audience-specific summaries",
        },
        {
            "contract_name": "release_qa_evidence",
            "current_version": RELEASE_QA_EVIDENCE_SCHEMA_VERSION,
            "supported_versions": [RELEASE_QA_EVIDENCE_SCHEMA_VERSION],
            "entrypoint": "normalize_release_qa_evidence",
            "normalization_strategy": "normalize_on_read",
            "notes": "Nested release QA evidence contract for smoke, assertion QA, screenshot diff, and release gate metrics",
        },
        {
            "contract_name": "release_promotion_history",
            "current_version": RELEASE_PROMOTION_HISTORY_SCHEMA_VERSION,
            "supported_versions": [RELEASE_PROMOTION_HISTORY_SCHEMA_VERSION],
            "entrypoint": "normalize_release_promotion_history",
            "normalization_strategy": "normalize_on_read",
            "notes": "P17 persisted promotion history with decision, executor, target channel, plan snapshot, and audit metadata",
        },
        {
            "contract_name": "release_execution_status",
            "current_version": RELEASE_EXECUTION_STATUS_SCHEMA_VERSION,
            "supported_versions": [RELEASE_EXECUTION_STATUS_SCHEMA_VERSION],
            "entrypoint": "normalize_release_execution_status",
            "normalization_strategy": "normalize_on_read",
            "notes": "P18 rollout execution contract covering dry run, canary, full rollout, rollback, and active release channel bindings",
        },
        {
            "contract_name": "governance_policy",
            "current_version": GOVERNANCE_POLICY_SCHEMA_VERSION,
            "supported_versions": [GOVERNANCE_POLICY_SCHEMA_VERSION],
            "entrypoint": "build_governance_policy",
            "normalization_strategy": "authoritative_static_contract",
            "notes": "P3 project governance rules, evidence catalog, and path policy",
        },
        {
            "contract_name": "change_admission",
            "current_version": CHANGE_ADMISSION_SCHEMA_VERSION,
            "supported_versions": [CHANGE_ADMISSION_SCHEMA_VERSION],
            "entrypoint": "build_change_admission",
            "normalization_strategy": "evaluate_on_read",
            "notes": "P3 admission gate for change type, evidence, paths, quality dashboard, and migrations",
        },
        {
            "contract_name": "governance_enforcement",
            "current_version": GOVERNANCE_ENFORCEMENT_SCHEMA_VERSION,
            "supported_versions": [GOVERNANCE_ENFORCEMENT_SCHEMA_VERSION],
            "entrypoint": "build_governance_enforcement",
            "normalization_strategy": "evaluate_on_read",
            "notes": "P4 executable admission gate with mode, blocking checks, and CI exit code",
        },
        {
            "contract_name": "production_scenarios",
            "current_version": PRODUCTION_SCENARIO_SCHEMA_VERSION,
            "supported_versions": [PRODUCTION_SCENARIO_SCHEMA_VERSION],
            "entrypoint": "list_production_scenarios",
            "normalization_strategy": "authoritative_static_contract",
            "notes": "P5 production validation scenario catalog with required paths, evidence, and gates",
        },
        {
            "contract_name": "production_readiness",
            "current_version": PRODUCTION_READINESS_SCHEMA_VERSION,
            "supported_versions": [PRODUCTION_READINESS_SCHEMA_VERSION],
            "entrypoint": "build_production_readiness",
            "normalization_strategy": "evaluate_on_read",
            "notes": "P5 strict/advisory production-scale readiness gate for real project handoff",
        },
        {
            "contract_name": "release_candidate_checklist",
            "current_version": RELEASE_CANDIDATE_CHECKLIST_SCHEMA_VERSION,
            "supported_versions": [RELEASE_CANDIDATE_CHECKLIST_SCHEMA_VERSION],
            "entrypoint": "build_release_candidate_checklist",
            "normalization_strategy": "evaluate_on_read",
            "notes": "P15 release candidate checklist derived from release manifest, QA gate, rollback, and production readiness",
        },
        {
            "contract_name": "agent_provider_compatibility",
            "current_version": AGENT_PROVIDER_COMPAT_SCHEMA_VERSION,
            "supported_versions": [AGENT_PROVIDER_COMPAT_SCHEMA_VERSION],
            "entrypoint": "build_agent_compatibility_matrix",
            "normalization_strategy": "evaluate_on_read",
            "notes": "P6 compatibility matrix for Codex, IDEs, API agents, MCP bridges, and local LLMs",
        },
        {
            "contract_name": "feature_context",
            "current_version": FEATURE_CONTEXT_SCHEMA_VERSION,
            "supported_versions": [FEATURE_CONTEXT_SCHEMA_VERSION],
            "entrypoint": "build_task_feature_context",
            "normalization_strategy": "normalize_on_read",
            "notes": "Task.context feature tracking, acceptance checklist, review state",
        },
        {
            "contract_name": "quality_gate",
            "current_version": QUALITY_GATE_SCHEMA_VERSION,
            "supported_versions": [QUALITY_GATE_SCHEMA_VERSION],
            "entrypoint": "normalize_quality_gate",
            "normalization_strategy": "normalize_on_read",
            "notes": "Release QA / performance gate checks and metrics",
        },
        {
            "contract_name": "release_summary",
            "current_version": RELEASE_SUMMARY_SCHEMA_VERSION,
            "supported_versions": [RELEASE_SUMMARY_SCHEMA_VERSION],
            "entrypoint": "normalize_release_summary",
            "normalization_strategy": "normalize_on_read",
            "notes": "Build metadata, release notes, manifest, rollback hint",
        },
        {
            "contract_name": "skill_result",
            "current_version": SKILL_RESULT_SCHEMA_VERSION,
            "supported_versions": [SKILL_RESULT_SCHEMA_VERSION],
            "entrypoint": "record_skill_result_on_task",
            "normalization_strategy": "normalize_on_write",
            "notes": "Per-skill validation, rollback, artifact summary, quality gate",
        },
    ]
    return {
        "schema_version": CONTRACT_CATALOG_SCHEMA_VERSION,
        "contracts": contracts,
        "migration_entrypoints": [
            {
                "name": item["entrypoint"],
                "contract_name": item["contract_name"],
                "target_version": item["current_version"],
                "strategy": item["normalization_strategy"],
            }
            for item in contracts
        ],
    }
